"""Tests for question grouping boundaries."""

from __future__ import annotations

import unittest

import pymupdf as fitz

from utils.question_extractor.pdf_reader import TextLine
from utils.question_extractor.question_detector import split_question_lines


def line(text: str, y: float) -> TextLine:
    return TextLine(1, text, fitz.Rect(50, y, 400, y + 10))


class QuestionDetectorTests(unittest.TestCase):
    def test_end_marker_and_following_text_are_not_grouped(self) -> None:
        groups = split_question_lines([
            line("Q1. Pick one", 20),
            line("a) One", 40),
            line("--- End of Quiz ---", 60),
            line("Generated by the quiz tool", 80),
        ])
        self.assertEqual(len(groups), 1)
        self.assertEqual([item.text for item in groups[0][2]], ["Pick one", "a) One"])


if __name__ == "__main__":
    unittest.main()
